### ISSUE TITLE
Trying to use GetCBuildings from MemoryAccess to pull building information from current frame.

### ISSUE THREAD

**Issue by foxtail44** [CamxxCore/MapInfoTool#1]
Hello!

First off, thank you for your outstanding work.

I'm trying to use your memory manipulation in my project to pull building info from the game.

I'm calling MapInfoTool.Memory.MemoryAccess.GetCBuildings() like so:

```csharp
IEnumerable<CBuildingWrapped> buildings = MapInfoTool.Memory.MemoryAccess.GetCBuildings();

foreach (var b in buildings) tools.Logging.log(b.ModelName);

```

where `log` is just a function that appends text to a txt file.
I get this error:

```csharp
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at System.Runtime.InteropServices.Marshal.ReadIntPtr(IntPtr ptr)
   at MapInfoTool.Memory.MemoryAccess.<GetCBuildings>d__19.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at BuildingCounter.BuildingWorks.OnKeyUp(Object sender, KeyEventArgs e)
```
I haven't found anything helpful on the web, and it would help alot if I could have this working.

Thanks once again,
F

**Comment by foxtail44** [comment]
OK, so I figured I had to run `MemoryAccess.MainInit()` before calling that. Now it seems to work!
Getting a thread was being aborted error, but it should be easy to fix.

**Comment by CamxxCore** [comment]
Glad you got things figured out. Should I consider this solved/ closed?

**Comment by foxtail44** [comment]
Yes, thank you!
